### ISSUE TITLE
While submitting and retrieving, getting this error: __cxa_thread_call_dtors: dtr 0x8019e4a30 from unloaded dso, skipping

### ISSUE THREAD

**Issue by yurivict** [sim590/dpaste#12]
```
__cxa_thread_call_dtors: dtr 0x8019e4a30 from unloaded dso, skipping
```

It doesn't appear that anything is actually pasted, retrieval operation returns silently without doing anything.

Version 0.3.3
FreeBSD 11.2 amd64

**Comment by sim590** [comment]
> While submitting and retrieving

You're saying that nothing works on your side? Neither both operations (without encryption)? Can you specify the exact steps you're taking to get there (compilation, and program call on the command line)?

**EDIT**: According to #11 and/or #13, you don't seem to be able to compile. Therefore, I'd be interested to know the context in which you've run the program, hence my question above.

Have you tried running unit tests? Would you mind printing the output of the following:

```sh
./autogen.sh && ./configure --enable-tests && make test
```

**Comment by sim590** [comment]
Since this issue is stale, I will close it. If you have more info, feel free to reopen if it still does this on 0.4.0.
