### ISSUE TITLE
Packaging: Debian, ArchLinux

### ISSUE THREAD

**Issue by sim590** [sim590/dpaste#2]
## Debian

I have a package that is being reviewed for version 0.3.3.

- [ ] Uploaded to official repository;

## ArchLinux

For the moment, only AUR is supported. I'd appreciate having official package in ArchLinux.

**Comment by sim590** [comment]
I'm leaving an update about Debian: the review process has somewhat stopped after no response from me due to work related constraints. I will check on this soon.

**Comment by sim590** [comment]
The Debian package is now again in the process of being reviewed. I will update when this is done.

**Comment by smu-ggl** [comment]
Debian now has 0.4.0-1 - which I guess should close this issue?

**Comment by sim590** [comment]
Yeah. I think you are right. Although, I have not maintained the package on Debian for a while, I don't know what has happened to it.

On arch's side, updating AUR is always easy enough and if something is wrong with it someone could feel free to reopen this issue.
